#!/usr/bin/env bash
set -e

export MRLINUX_FLAKE_REF="github:fd/mrlinux"
export MRHOME_FLAKE_REF="github:mrhenry/home-manager"
export MRNIX_CACHE_URL="https://alpha.pigeon-blues.ts.net/attic/release-public"
export MRNIX_CACHE_KEY="release-public:RLOvxX/CMLa6ffQ5oUDXA5zt/qjMN3u4z6GW+xZ1gWw="

function collect_system_type {
    system="$(uname)"
}

function collect_environment_info_macos {
    username="$USER"
    uid="$(id -u)"
    gid="$uid"
    if [[ -d ~/.ssh ]]; then
        sshKeys="$(find ~/.ssh -name 'id_*.pub' -exec cat {} \; | awk '{print "\"" $1 " " $2 "\""}')"
    else
        echo "No SSH keys found" > /dev/stderr
        exit 1
    fi
}

function collect_environment_info_linux {
    username="$USER"
    uid="$(id -u)"
    gid="$(id -g)"
    if [[ -d ~/.ssh ]]; then
        sshKeys="$(find ~/.ssh -name 'id_*.pub' -exec cat {} \; | awk '{print "\"" $1 " " $2 "\""}')"
    else
        echo "No SSH keys found" > /dev/stderr
        exit 1
    fi
}

function test_system_linux {
    # Make sue LXD is installed
    if ! command -v lxd > /dev/null; then
        echo "LXD is not installed" > /dev/stderr
        exit 1
    fi

    # Make sure LXC is installed
    if ! command -v lxc > /dev/null; then
        echo "LXC is not installed" > /dev/stderr
        exit 1
    fi

    # Make sure Nix is installed
    if ! command -v nix > /dev/null; then
        echo "Nix is not installed" > /dev/stderr
        exit 1
    fi
}

function test_system_macos {
    # Make sure OrbStack is installed (orb command)
    if ! command -v orb > /dev/null; then
        echo "OrbStack is not installed" > /dev/stderr
        exit 1
    fi
}

function lxc_ip_address {
    local containerName="$1"
    lxc list -c 4 -f compact name="$containerName" | tail -1 | sed 's|(.*)||' | awk '{print $1}'
}

function init_linux {
    local containerName="$1"

    nix run .#lxc-import-image || true

    mkdir -p $HOME/.config/mrlinux

    lxc init mrlinux "$containerName" -c security.nesting=true -c security.privileged=true
    lxc config device add "$containerName" host-home disk source=$HOME path=/host$HOME shift=true readonly=true
    lxc config device add "$containerName" user-src disk source=$HOME/src path=$HOME/src shift=true
    lxc config device add "$containerName" user-config disk source=$HOME/.config/mrlinux path=$HOME/.config-mrlinux shift=true
    
    lxc start "$containerName"

    # Wait for IP address to be assigned
    while [[ -z "$(lxc_ip_address "$containerName")" ]]; do
        sleep 1
    done



    # Install the extended OS
    lxc exec "$containerName" -- nix run \
      --extra-experimental-features "nix-command flakes" \
      --extra-substituters "$MRNIX_CACHE_URL" \
      --extra-trusted-public-keys "$MRNIX_CACHE_KEY" \
      "${MRLINUX_FLAKE_REF}#install-extended-os" \
      -- \
      --mrlinux-flake-ref "$MRLINUX_FLAKE_REF" \
      --mrlinux-cache-url "$MRNIX_CACHE_URL" \
      --mrlinux-cache-key "$MRNIX_CACHE_KEY" \
      --container-name "$containerName" \
      --stack "lxc" \
      --username "$username" \
      --uid "$uid" \
      --gid "$gid" \
      --ssh-keys "$sshKeys"

    # Restart the container to apply the changes
    lxc restart "$containerName"

    # Wait for IP address to be assigned
    while [[ -z "$(lxc_ip_address "$containerName")" ]]; do
        sleep 1
    done

    # Wait for SSH to be available, while ignoring the host key
    # while ! ssh -o StrictHostKeyChecking=no "$username@$(lxc_ip_address "$containerName")" true; do
    #     sleep 1
    # done

    # Reset SSH
    ssh-keygen -f "$HOME/.ssh/known_hosts" -R "$(lxc_ip_address "$containerName")"
    # Tell ssh to trust the container
    ssh-keyscan -H "$(lxc_ip_address "$containerName")" >> "$HOME/.ssh/known_hosts"

    # Install the Home Manager configuration
    ssh "$username@$(lxc_ip_address "$containerName")" nix run "$MRHOME_FLAKE_REF" \
        --extra-substituters "$MRNIX_CACHE_URL" \
        --extra-trusted-public-keys "$MRNIX_CACHE_KEY"
}

function init_macos {
    local containerName="$1"

    mkdir -p $HOME/.config/mrlinux

    orbctl create nixos "$containerName"

    # Install the extended OS
    orb run -m "$containerName" -u root nix run \
      --extra-experimental-features "nix-command flakes" \
      --extra-substituters "$MRNIX_CACHE_URL" \
      --extra-trusted-public-keys "$MRNIX_CACHE_KEY" \
      "${MRLINUX_FLAKE_REF}#install-extended-os" \
      -- \
      --mrlinux-flake-ref "$MRLINUX_FLAKE_REF" \
      --mrlinux-cache-url "$MRNIX_CACHE_URL" \
      --mrlinux-cache-key "$MRNIX_CACHE_KEY" \
      --container-name "$containerName" \
      --stack "orb" \
      --username "$username" \
      --uid "$uid" \
      --gid "$gid" \
      --ssh-keys "$sshKeys"
    
    # Restart the container to apply the changes
    orbctl restart "$containerName"

    sleep 5

    # Install the Home Manager configuration
    ssh "$username@$containerName@orb" nix run "$MRHOME_FLAKE_REF" \
        --extra-substituters "$MRNIX_CACHE_URL" \
        --extra-trusted-public-keys "$MRNIX_CACHE_KEY"
}

function run_create {
    # Make sure at most one argument is passed
    if [ "$#" -gt "1" ]; then
        echo "Too many arguments" > /dev/stderr
        bail_with_usage
    fi

    # Set container name to the first argument or default to "mrlinux"
    local containerName="${1:-mrlinux}"

    echo "System: $system" > /dev/stderr
    case "$system" in
        Linux)
            collect_environment_info_linux
            test_system_linux
            init_linux "$containerName"
            ;;
        Darwin)
            collect_environment_info_macos
            test_system_macos
            init_macos "$containerName"
            ;;
        *)
            echo "Unsupported system: $system" > /dev/stderr
            exit 1
            ;;
    esac
}

function run_delete {
    # Make sure at most one argument is passed
    if [ "$#" -gt "1" ]; then
        echo "Too many arguments" > /dev/stderr
        bail_with_usage
    fi

    # Set container name to the first argument or default to "mrlinux"
    local containerName="${1:-mrlinux}"

    case "$system" in
        Linux)
            lxc delete "$containerName" -f
            ;;
        Darwin)
            orbctl delete "$containerName"
            ;;
        *)
            echo "Unsupported system: $system" > /dev/stderr
            exit 1
            ;;
    esac
}

function run_restart {
    # Make sure at most one argument is passed
    if [ "$#" -gt "1" ]; then
        echo "Too many arguments" > /dev/stderr
        bail_with_usage
    fi

    # Set container name to the first argument or default to "mrlinux"
    local containerName="${1:-mrlinux}"

    case "$system" in
        Linux)
            lxc restart "$containerName" -f

            # Wait for IP address to be assigned
            while [[ -z "$(lxc_ip_address "$containerName")" ]]; do
                sleep 1
            done
            ;;
        Darwin)
            orbctl restart "$containerName"
            ;;
        *)
            echo "Unsupported system: $system" > /dev/stderr
            exit 1
            ;;
    esac
}

function run_code {
    # Setup paths as an empty list
    local paths=()

    # Loop over arguments
    while [ "$#" -gt "0" ]; do
        case "$1" in
            -m)
                shift
                local containerName="$1"
                shift

                # containerName is set
                if [ -z "$containerName" ]; then
                    echo "Missing container name" > /dev/stderr
                    bail_with_usage
                fi
                ;;
            -w|--wait)
                local wait="true"
                shift
                ;;
            -n|--new-window)
                local newWindow="true"
                shift
                ;;
            -r|--reuse-window)
                local reuseWindow="true"
                shift
                ;;
            -*)
                echo "Unknown flag: $1" > /dev/stderr
                bail_with_usage
                ;;
            *)
                # Append the path to the list of paths
                paths+=("$(realpath "$1")")
                shift
                ;;
        esac
    done

    # if containerName is not set, set it to "mrlinux"
    if [ -z "$containerName" ]; then
        local containerName="mrlinux"
    fi

    # If paths is empty append the current directory
    if [ "${#paths[@]}" == "0" ]; then
        paths+=("$(realpath .)")
    fi

    # Let args be an empty list
    local args=()

    # If wait is true append the --wait flag
    if [ "$wait" == "true" ]; then
        args+=("--wait")
    fi

    # If newWindow is true append the --new-window flag
    if [ "$newWindow" == "true" ]; then
        args+=("--new-window")
    fi

    # If reuseWindow is true append the --reuse-window flag
    if [ "$reuseWindow" == "true" ]; then
        args+=("--reuse-window")
    fi

    # Append all the paths to args
    for path in "${paths[@]}"; do
        args+=("$path")
    done

    case "$system" in
        Linux)
            exec code --remote "ssh-remote+$USER@$(lxc_ip_address "$containerName")" "${args[@]}"
            ;;
        Darwin)
            exec code --remote "ssh-remote+$USER@$containerName@orb" "${args[@]}"
            ;;
        *)
            echo "Unsupported system: $system" > /dev/stderr
            exit 1
            ;;
    esac
}

collect_system_type

function bail_with_usage {
    echo "mrlinuxctl create [<machine>]"
    echo "mrlinuxctl delete [<machine>]"
    echo "mrlinuxctl reset [<machine>]"
    echo "mrlinuxctl restart [<machine>]"
    echo "mrlinuxctl code [-m <machine>] [-w|--wait] [-n|--new-window] [-r|--reuse-window] [path...]"
    exit 1
}

if [ "$#" == "0" ]; then
    bail_with_usage
fi
case "$1" in
    create)
        shift
        run_create "$@"
        ;;
    delete)
        shift
        run_delete "$@"
        ;;
    reset)
        shift
        run_delete "$@" || true
        run_create "$@"
        ;;
    restart)
        shift
        run_restart "$@"
        ;;
    code)
        shift
        run_code "$@"
        ;;
    *)
        bail_with_usage
        ;;
esac
